// Country slug to continent mapping
export const COUNTRY_CONTINENTS: { [key: string]: string } = {
  // Africa
  'algeria': 'Africa',
  'angola': 'Africa',
  'benin': 'Africa',
  'botswana': 'Africa',
  'burkina-faso': 'Africa',
  'burundi': 'Africa',
  'cameroon': 'Africa',
  'cape-verde': 'Africa',
  'central-african-republic': 'Africa',
  'chad': 'Africa',
  'comoros': 'Africa',
  'congo': 'Africa',
  'democratic-republic-of-congo': 'Africa',
  'cote-divoire': 'Africa',
  'djibouti': 'Africa',
  'egypt': 'Africa',
  'equatorial-guinea': 'Africa',
  'eritrea': 'Africa',
  'eswatini': 'Africa',
  'ethiopia': 'Africa',
  'gabon': 'Africa',
  'republic-of-the-gambia': 'Africa',
  'ghana': 'Africa',
  'guinea': 'Africa',
  'guinea-bissau': 'Africa',
  'kenya': 'Africa',
  'lesotho': 'Africa',
  'liberia': 'Africa',
  'libya': 'Africa',
  'madagascar': 'Africa',
  'malawi': 'Africa',
  'mali': 'Africa',
  'mauritania': 'Africa',
  'mauritius': 'Africa',
  'mayotte': 'Africa',
  'morocco': 'Africa',
  'mozambique': 'Africa',
  'namibia': 'Africa',
  'niger': 'Africa',
  'nigeria': 'Africa',
  'reunion': 'Africa',
  'rwanda': 'Africa',
  'saint-tome-sao-tome-and-principe': 'Africa',
  'senegal': 'Africa',
  'seychelles': 'Africa',
  'sierra-leone': 'Africa',
  'somalia': 'Africa',
  'somaliland': 'Africa',
  'south-africa': 'Africa',
  'south-sudan': 'Africa',
  'sudan': 'Africa',
  'tanzania': 'Africa',
  'togo': 'Africa',
  'tunisia': 'Africa',
  'uganda': 'Africa',
  'western-sahara': 'Africa',
  'zambia': 'Africa',
  'zimbabwe': 'Africa',

  // Asia
  'afghanistan': 'Asia',
  'armenia': 'Asia',
  'azerbaijan': 'Asia',
  'bahrain': 'Asia',
  'bangladesh': 'Asia',
  'bhutan': 'Asia',
  'brunei-darussalam': 'Asia',
  'cambodia': 'Asia',
  'china': 'Asia',
  'china-hong-kong-macao': 'Asia',
  'cyprus': 'Asia',
  'georgia': 'Asia',
  'india': 'Asia',
  'indonesia': 'Asia',
  'iran': 'Asia',
  'iraq': 'Asia',
  'israel': 'Asia',
  'japan': 'Asia',
  'jordan': 'Asia',
  'kazakhstan': 'Asia',
  'democratic-republic-of-korea': 'Asia',
  'republic-of-korea': 'Asia',
  'kuwait': 'Asia',
  'kyrgyzstan': 'Asia',
  'laos': 'Asia',
  'lebanon': 'Asia',
  'malaysia': 'Asia',
  'maldives': 'Asia',
  'mongolia': 'Asia',
  'myanmar-burma': 'Asia',
  'nepal': 'Asia',
  'oman': 'Asia',
  'pakistan': 'Asia',
  'palestine': 'Asia',
  'philippines': 'Asia',
  'qatar': 'Asia',
  'russian-federation': 'Asia',
  'saudi-arabia': 'Asia',
  'singapore': 'Asia',
  'sri-lanka': 'Asia',
  'syria': 'Asia',
  'taiwan': 'Asia',
  'tajikistan': 'Asia',
  'thailand': 'Asia',
  'timor-leste': 'Asia',
  'turkiye': 'Asia',
  'turkmenistan': 'Asia',
  'united-arab-emirates': 'Asia',
  'uzbekistan': 'Asia',
  'vietnam': 'Asia',
  'yemen': 'Asia',

  // Europe
  'albania': 'Europe',
  'andorra': 'Europe',
  'austria': 'Europe',
  'belarus': 'Europe',
  'belgium': 'Europe',
  'bosnia-and-herzegovina': 'Europe',
  'bulgaria': 'Europe',
  'croatia': 'Europe',
  'czech-republic': 'Europe',
  'denmark': 'Europe',
  'estonia': 'Europe',
  'faroe-islands': 'Europe',
  'finland': 'Europe',
  'france': 'Europe',
  'germany': 'Europe',
  'great-britain': 'Europe',
  'greece': 'Europe',
  'greenland': 'Europe',
  'hungary': 'Europe',
  'iceland': 'Europe',
  'ireland': 'Europe',
  'italy': 'Europe',
  'kosovo': 'Europe',
  'latvia': 'Europe',
  'liechtenstein': 'Europe',
  'lithuania': 'Europe',
  'luxembourg': 'Europe',
  'malta': 'Europe',
  'moldova': 'Europe',
  'monaco': 'Europe',
  'montenegro': 'Europe',
  'the-netherlands': 'Europe',
  'republic-of-north-macedonia': 'Europe',
  'norway': 'Europe',
  'poland': 'Europe',
  'portugal': 'Europe',
  'romania': 'Europe',
  'san-marino': 'Europe',
  'serbia': 'Europe',
  'slovak-republic-slovakia': 'Europe',
  'slovenia': 'Europe',
  'spain': 'Europe',
  'sweden': 'Europe',
  'switzerland': 'Europe',
  'ukraine': 'Europe',
  'holy-see': 'Europe',

  // North America
  'antigua-and-barbuda': 'North America',
  'bahamas': 'North America',
  'barbados': 'North America',
  'belize': 'North America',
  'bermuda': 'North America',
  'canada': 'North America',
  'cayman-islands': 'North America',
  'costa-rica': 'North America',
  'cuba': 'North America',
  'dominica': 'North America',
  'dominican-republic': 'North America',
  'el-salvador': 'North America',
  'grenada': 'North America',
  'guadeloupe': 'North America',
  'guatemala': 'North America',
  'haiti': 'North America',
  'honduras': 'North America',
  'jamaica': 'North America',
  'martinique': 'North America',
  'mexico': 'North America',
  'montserrat': 'North America',
  'nicaragua': 'North America',
  'panama': 'North America',
  'puerto-rico': 'North America',
  'saint-barthelemy': 'North America',
  'saint-kitts-and-nevis': 'North America',
  'saint-lucia': 'North America',
  'saint-martin': 'North America',
  'sint-maarten': 'North America',
  'saint-pierre-and-miquelon': 'North America',
  'saint-vincent-and-the-grenadines': 'North America',
  'trinidad-and-tobago': 'North America',
  'turks-and-caicos-islands': 'North America',
  'united-states-of-america': 'North America',
  'virgin-islands-uk': 'North America',
  'virgin-islands-us': 'North America',
  'anguilla': 'North America',

  // South America
  'argentina': 'South America',
  'bolivia': 'South America',
  'brazil': 'South America',
  'chile': 'South America',
  'colombia': 'South America',
  'ecuador': 'South America',
  'french-guiana': 'South America',
  'guyana': 'South America',
  'paraguay': 'South America',
  'peru': 'South America',
  'suriname': 'South America',
  'uruguay': 'South America',
  'venezuela': 'South America',

  // Oceania
  'australia': 'Oceania',
  'cook-islands': 'Oceania',
  'fiji': 'Oceania',
  'kiribati': 'Oceania',
  'marshall-islands': 'Oceania',
  'federated-states-of-micronesia': 'Oceania',
  'nauru': 'Oceania',
  'new-caledonia': 'Oceania',
  'new-zealand': 'Oceania',
  'niue': 'Oceania',
  'palau': 'Oceania',
  'papua-new-guinea': 'Oceania',
  'samoa': 'Oceania',
  'solomon-islands': 'Oceania',
  'tonga': 'Oceania',
  'tuvalu': 'Oceania',
  'vanuatu': 'Oceania',
  'french-polynesia': 'Oceania',
  'wallis-and-futuna': 'Oceania',
  'norfolk-island': 'Oceania',

  // Antarctica & Other
  'antarctica': 'Antarctica',
  'french-southern-and-antarctic-lands': 'Antarctica',
};

export function getContinent(slug: string): string {
  return COUNTRY_CONTINENTS[slug] || 'Other';
}

export function groupByContinent(countries: { slug: string; status: string }[]): { [continent: string]: { slug: string; status: string }[] } {
  const grouped: { [continent: string]: { slug: string; status: string }[] } = {};
  
  countries.forEach(country => {
    const continent = getContinent(country.slug);
    if (!grouped[continent]) {
      grouped[continent] = [];
    }
    grouped[continent].push(country);
  });
  
  return grouped;
}
